### ISSUE TITLE
state bug in storm: Invalid decrement counter cannot be less than 0

### ISSUE THREAD

**Issue by johnynek** [twitter/summingbird#747]
It *seems* to me like we are acking more things than we expect to be there. This is killing the nodes.

Seems like some assumption about storm or our code is incorrect.

This is on storm 0.9.3 (yeah, I know...)

```
2017-09-12 02:42:40 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: java.lang.Exception: Invalid decrement counter cannot be less than 0
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:128) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:99) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.executor$fn__3441$fn__3453$fn__3500.invoke(executor.clj:748) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463) ~[storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.Exception: Invalid decrement counter cannot be less than 0
	at com.twitter.summingbird.online.executor.InputState$State.decrBy(InputState.scala:60) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.InputState$State.decr(InputState.scala:69) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.InputState$$anonfun$2.apply(InputState.scala:93) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.InputState$$anonfun$2.apply(InputState.scala:93) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.AtomicStateTransformer$$anonfun$update$1.apply(InputState.scala:37) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.AtomicStateTransformer$$anonfun$update$1.apply(InputState.scala:37) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.AtomicStateTransformer.updateWithState(InputState.scala:29) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.AtomicStateTransformer.update(InputState.scala:37) ~[stormjar.jar:na]
	at com.twitter.summingbird.online.executor.InputState.ack(InputState.scala:93) ~[stormjar.jar:na]
	at com.twitter.summingbird.storm.BaseBolt$$anonfun$com$twitter$summingbird$storm$BaseBolt$$finish$3.apply(BaseBolt.scala:169) ~[stormjar.jar:na]
	at com.twitter.summingbird.storm.BaseBolt$$anonfun$com$twitter$summingbird$storm$BaseBolt$$finish$3.apply(BaseBolt.scala:169) ~[stormjar.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:392) ~[stormjar.jar:na]
	at com.twitter.summingbird.storm.BaseBolt.com$twitter$summingbird$storm$BaseBolt$$finish(BaseBolt.scala:169) ~[stormjar.jar:na]
	at com.twitter.summingbird.storm.BaseBolt$$anonfun$execute$1.apply(BaseBolt.scala:147) ~[stormjar.jar:na]
	at com.twitter.summingbird.storm.BaseBolt$$anonfun$execute$1.apply(BaseBolt.scala:144) ~[stormjar.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:392) ~[stormjar.jar:na]
	at com.twitter.summingbird.storm.BaseBolt.execute(BaseBolt.scala:144) ~[stormjar.jar:na]
	at backtype.storm.daemon.executor$fn__3441$tuple_action_fn__3443.invoke(executor.clj:633) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.executor$mk_task_receiver$fn__3364.invoke(executor.clj:404) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.disruptor$clojure_handler$reify__1447.onEvent(disruptor.clj:58) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:125) ~[storm-core-0.9.3.jar:0.9.3]
	... 6 common frames omitted
```

**Comment by johnynek** [comment]
this *seems* to only get triggered if the store has already failed in a weird way. Closing for now.
